<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ClaimAdministrator;

class ClaimAdministrators extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    /* `medvorth_final_db`.`claim_administrators` */



    public function run()
    {
        //
        $claimAdministrators = array(
            array('id' => '1','name' => 'Farmers Company','alias' => NULL,'company_type_id' => '1','description' => 'test','payer_id' => NULL,'start_time' => '08:15:00','end_time' => '19:15:00','email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-30 22:16:08','updated_at' => '2022-01-31 16:07:50','deleted_at' => NULL),
            array('id' => '2','name' => 'cipasi@mailinator.com','alias' => 'mozetaqa@mailinator.com','company_type_id' => '2','description' => 'Consectetur fugit','payer_id' => 'rakojoty@mailinator.com','start_time' => '22:02:00','end_time' => '07:28:00','email' => 'guhiqicyj@mailinator.com','website' => 'wivifuje@mailinator.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Quo ipsam commodo ad','is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-30 22:19:21','updated_at' => '2023-09-14 14:38:03','deleted_at' => NULL),
            array('id' => '3','name' => 'test nane','alias' => NULL,'company_type_id' => '1','description' => 'test fdf','payer_id' => NULL,'start_time' => NULL,'end_time' => NULL,'email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-30 23:57:15','updated_at' => '2023-07-02 19:19:15','deleted_at' => '2023-07-02 19:19:15'),
            array('id' => '4','name' => 'Farmers Insurance','alias' => NULL,'company_type_id' => '1','description' => 'testdescription','payer_id' => NULL,'start_time' => '07:00:00','end_time' => '20:33:00','email' => NULL,'website' => 'https://www.farmers.com','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 00:33:33','updated_at' => '2023-07-02 19:19:29','deleted_at' => '2023-07-02 19:19:29'),
            array('id' => '5','name' => 'Farmers Insurance 2','alias' => NULL,'company_type_id' => '1','description' => NULL,'payer_id' => NULL,'start_time' => NULL,'end_time' => NULL,'email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 00:39:42','updated_at' => '2023-06-29 21:32:26','deleted_at' => '2023-06-29 21:32:26'),
            array('id' => '6','name' => 'Berkshire Hathaway Homestate Companies 6','alias' => 'BHHC, Berkshire Hathaway','company_type_id' => '1','description' => NULL,'payer_id' => 'db78950','start_time' => '07:00:00','end_time' => '20:00:00','email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 17:08:58','updated_at' => '2022-02-01 18:32:53','deleted_at' => NULL),
            array('id' => '7','name' => 'Berkshire Hathaway Homestate Companies','alias' => 'BHHC, Berkshire Hathaway','company_type_id' => '1','description' => NULL,'payer_id' => NULL,'start_time' => NULL,'end_time' => NULL,'email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 17:18:11','updated_at' => '2023-06-29 21:32:31','deleted_at' => '2023-06-29 21:32:31'),
            array('id' => '8','name' => 'test','alias' => NULL,'company_type_id' => '1','description' => NULL,'payer_id' => NULL,'start_time' => NULL,'end_time' => NULL,'email' => NULL,'website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 17:47:03','updated_at' => '2023-07-02 19:08:08','deleted_at' => '2023-07-02 19:08:08'),
            array('id' => '9','name' => 'Berkshire Hathaway Homestate Companies','alias' => NULL,'company_type_id' => '1','description' => NULL,'payer_id' => NULL,'start_time' => '08:01:00','end_time' => '17:00:00','email' => NULL,'website' => 'https://www.bhhc.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2022-01-31 18:51:01','updated_at' => '2022-01-31 18:51:01','deleted_at' => NULL),
            array('id' => '10','name' => 'ASG - Abercrombie, Simmons & Gillette','alias' => 'ASG - Abercrombie, Simmon','company_type_id' => '1','description' => 'aaaaaa','payer_id' => NULL,'start_time' => '20:52:00','end_time' => '14:57:00','email' => 'ss@gmail.com','website' => NULL,'bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-04-15 20:52:53','updated_at' => '2023-04-15 20:52:53','deleted_at' => NULL),
            array('id' => '11','name' => 'test for new change for claim administratior','alias' => 'test for new change for c','company_type_id' => '1','description' => 'fdsf','payer_id' => 'dev1','start_time' => '23:01:00','end_time' => '18:08:00','email' => 'tets@gmail.com','website' => 'www.google.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'dfsdf','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-05-15 00:01:59','updated_at' => '2023-07-02 19:08:02','deleted_at' => '2023-07-02 19:08:02'),
            array('id' => '38','name' => 'test patient singh singh','alias' => 'cd','company_type_id' => '1','description' => 'sdasd','payer_id' => 'xs','start_time' => '22:35:00','end_time' => '12:35:00','email' => 'priyapriyanka.pk1985@gmail.com','website' => 'www.google.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'sfs','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-05-15 01:35:36','updated_at' => '2023-07-02 19:07:59','deleted_at' => '2023-07-02 19:07:59'),
            array('id' => '39','name' => 'de','alias' => 'sed','company_type_id' => '1','description' => 'fs','payer_id' => 'ss','start_time' => '22:36:00','end_time' => '23:36:00','email' => 'sde@gmail.com','website' => 'www.goog.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'sfsf','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-05-15 01:37:06','updated_at' => '2023-07-02 19:07:54','deleted_at' => '2023-07-02 19:07:54'),
            array('id' => '40','name' => 'de','alias' => 'asda','company_type_id' => '1','description' => 'sfsf','payer_id' => 'sd','start_time' => '22:39:00','end_time' => '23:39:00','email' => 'sde@gmail.com','website' => 'www.google.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'sfsf','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-05-15 01:40:01','updated_at' => '2023-07-02 19:07:51','deleted_at' => '2023-07-02 19:07:51'),
            array('id' => '41','name' => 'cd','alias' => NULL,'company_type_id' => '1','description' => 'drff','payer_id' => 'dev','start_time' => '21:43:00','end_time' => '23:43:00','email' => 'sde@gmail.com','website' => 'www.google.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'vffff','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-05-15 01:43:44','updated_at' => '2023-06-29 18:38:38','deleted_at' => '2023-06-29 18:38:38'),
            array('id' => '42','name' => 'CompTrust AGC Mutual Captive Insurance Company','alias' => 'Testing Name','company_type_id' => '1','description' => 'This is Testing Description','payer_id' => 'db90172','start_time' => NULL,'end_time' => NULL,'email' => 'jpsmoonstar@gmail.com','website' => 'www.merakircm.com','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => 'test clearing house','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-06-27 01:26:17','updated_at' => '2023-10-06 09:44:32','deleted_at' => NULL),
            array('id' => '43','name' => 'Acclamation Insurance Management Services','alias' => 'AIMS','company_type_id' => '1','description' => '-','payer_id' => 'mv64779','start_time' => '08:00:00','end_time' => '17:00:00','email' => 'Unavailable','website' => 'https://www.aims4claims.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '0','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => NULL,'time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-06-29 18:56:04','updated_at' => '2023-06-29 21:32:14','deleted_at' => '2023-06-29 21:32:14'),
            array('id' => '44','name' => 'Acclamation Insurance Management Services','alias' => 'AIMS','company_type_id' => '1','description' => '-','payer_id' => 'mv64779','start_time' => '08:00:00','end_time' => '17:00:00','email' => 'Unavailable','website' => 'https://www.aims4claims.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Roseville Office: (800) 444-6157','created_at' => '2023-06-29 18:56:26','updated_at' => '2023-12-04 09:34:18','deleted_at' => NULL),
            array('id' => '45','name' => 'AmTrust North America','alias' => 'AmTrust','company_type_id' => '1','description' => '-','payer_id' => 'mv97799','start_time' => '08:00:00','end_time' => '19:00:00','email' => 'Unavailable','website' => 'https://amtrustfinancial.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review
          Claims which are denied, closed, or in determination (contested) are not sent to Bill Review. Denial letters are sent directly to the provider from AmTrust adjuster. Contact the AmTrust adjuster directly regarding bills not on file reported by Bill Review.','is_active' => '1','admin_fax_no' => NULL,'admin_address' => NULL,'clearing_house' => 'Testing','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-06-29 23:07:42','updated_at' => '2023-10-09 14:36:09','deleted_at' => NULL),
            array('id' => '46','name' => 'OccuSure Claims Services','alias' => NULL,'company_type_id' => '1','description' => 'Entity receives, reviews and processes bills','payer_id' => 'EMAIL','start_time' => NULL,'end_time' => NULL,'email' => 'claims@occusure.com','website' => 'www.occusure.com','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => '(615) 377-4735','admin_address' => 'PO Box 682829, Franklin, TN 37068','clearing_house' => 'EMAILONLY','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-11-30 19:43:31','updated_at' => '2023-11-30 19:43:31','deleted_at' => NULL),
            array('id' => '47','name' => 'Farmers Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV78950','start_time' => '08:00:00','end_time' => '20:00:00','email' => 'Unavailable','website' => 'https://www.farmers.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Unavailable','admin_address' => 'PO Box 108843, Oklahoma City, OK 73101','clearing_house' => 'Clearing House','time_zone_type' => 'PST','bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 09:20:27','updated_at' => '2023-12-03 09:20:27','deleted_at' => NULL),
            array('id' => '48','name' => 'Gallagher Bassett Services Inc.','alias' => NULL,'company_type_id' => '1','description' => 'Starr Indemnity, Republic Group, CMC, Sompo Insurance, Sompo Global Risk','payer_id' => 'MV43094','start_time' => '08:00:00','end_time' => '20:00:00','email' => 'Unavailable','website' => 'https://www.gallagherbassett.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Unavailable','admin_address' => 'PO Box 2840, Clinton, IA 52733-2840','clearing_house' => 'Clearing House','time_zone_type' => 'PST','bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 09:25:31','updated_at' => '2023-12-03 09:25:31','deleted_at' => NULL),
            array('id' => '49','name' => 'Great West Casualty Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV66939','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://ssl.gwccnet.com/','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:35:50','updated_at' => '2023-12-03 10:55:14','deleted_at' => NULL),
            array('id' => '50','name' => 'H&H Claims Consultants','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV60822','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.hhclaims.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:37:35','updated_at' => '2023-12-03 10:37:35','deleted_at' => NULL),
            array('id' => '51','name' => 'IAT Insurance Group','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV79092','start_time' => '08:00:00','end_time' => '17:00:00','email' => 'Unavailable','website' => 'https://www.iatinsurancegroup.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => 'CST','bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:42:35','updated_at' => '2023-12-03 10:42:35','deleted_at' => NULL),
            array('id' => '52','name' => 'IHA Insurance Solutions','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV32807','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.ihainsurancesolutions.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:44:07','updated_at' => '2023-12-03 10:44:07','deleted_at' => NULL),
            array('id' => '53','name' => 'IMT Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV33605','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.imtins.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:46:06','updated_at' => '2023-12-03 10:46:06','deleted_at' => NULL),
            array('id' => '54','name' => 'Insurica Claim Management','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV99292','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://insurica.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:46:55','updated_at' => '2023-12-03 10:46:55','deleted_at' => NULL),
            array('id' => '55','name' => '3-Hab, Ltd.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV09600','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'http://www.3hab.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 10:57:03','updated_at' => '2023-12-03 10:57:03','deleted_at' => NULL),
            array('id' => '56','name' => 'A.G. Risk Management Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'V','start_time' => '09:00:00','end_time' => '17:00:00','email' => '-','website' => 'https://agrminc.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => 'EST','bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 11:00:06','updated_at' => '2023-12-03 11:00:06','deleted_at' => NULL),
            array('id' => '57','name' => 'A.I.M. Mutual Insurance Companies','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV50630','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.aimmutual.com/','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 11:02:21','updated_at' => '2023-12-03 11:08:00','deleted_at' => NULL),
            array('id' => '58','name' => 'Aasgard Summit Management Services','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV21498','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'http://www.aasgardsummit.net/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 11:10:28','updated_at' => '2023-12-03 11:10:28','deleted_at' => NULL),
            array('id' => '59','name' => 'Acadia Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV14206','start_time' => '07:30:00','end_time' => '16:30:00','email' => 'Unavailable','website' => 'https://www.acadiainsurance.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => 'EST','bill_portal' => NULL,'affiliated_entries' => NULL,'phone_number' => NULL,'created_at' => '2023-12-03 11:13:36','updated_at' => '2023-12-03 11:13:36','deleted_at' => NULL),
            array('id' => '60','name' => 'Accelerated Claims Services','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV65391','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'Unavailable','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (714) 647-1120','created_at' => '2023-12-04 09:18:03','updated_at' => '2023-12-04 09:18:03','deleted_at' => NULL),
            array('id' => '61','name' => 'Acuity Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV44280','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.acuity.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 242-7666','created_at' => '2023-12-04 09:37:06','updated_at' => '2023-12-04 09:37:06','deleted_at' => NULL),
            array('id' => '62','name' => 'Administrative Claim Service','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV51709','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'http://www.acsadjusting.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (763) 231-0051','created_at' => '2023-12-04 09:38:14','updated_at' => '2023-12-04 09:38:14','deleted_at' => NULL),
            array('id' => '63','name' => 'Administrative Concepts, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV00482','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: aciclaims@visit-aci.com','website' => 'https://www.acitpa.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Claim Status Portal: https://secure.visit-aci.com/','affiliated_entries' => '-','phone_number' => 'Main Line: (610) 293-9229','created_at' => '2023-12-04 09:39:08','updated_at' => '2023-12-04 09:39:08','deleted_at' => NULL),
            array('id' => '64','name' => 'Adminsure, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV74592','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://adminsure.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (909) 861-0816','created_at' => '2023-12-04 09:51:20','updated_at' => '2023-12-04 09:51:20','deleted_at' => NULL),
            array('id' => '65','name' => 'Advantage Workers Compensation Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV91669','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.wcf.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Claim Information Search: https://www.wcf.com/find-claim/','affiliated_entries' => 'WCF Insurance, Workers Compensation Fund','phone_number' => 'Main: (916) 888-1700','created_at' => '2023-12-04 10:00:02','updated_at' => '2023-12-04 10:00:02','deleted_at' => NULL),
            array('id' => '66','name' => 'Aegis Corporation','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV18609','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.aegis-corporation.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 236-6885','created_at' => '2023-12-04 10:02:03','updated_at' => '2023-12-04 10:02:03','deleted_at' => NULL),
            array('id' => '67','name' => 'Affirmative','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'Third-Party Administrator','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: claims@primeadministrators.com','website' => 'https://www.primeadministrators.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity does not receive bills, Third Party Bill Review receives bills directly','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'MV10463','phone_number' => 'Main: (559) 481-7100','created_at' => '2023-12-04 10:04:13','updated_at' => '2023-12-04 10:04:13','deleted_at' => NULL),
            array('id' => '68','name' => 'AIG Claims, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV19670','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.aig.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator processes and reviews bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Provider Bill Inquiry: https://www-236.aig.com/ePBIWeb/web/','affiliated_entries' => 'Chartis, Granite State Insurance Company','phone_number' => 'Main: (877) 802-5246 Claim Inquiries: (877) 802-5246 x4','created_at' => '2023-12-04 10:06:05','updated_at' => '2023-12-04 10:06:05','deleted_at' => NULL),
            array('id' => '69','name' => 'Airforce Insurance Fund','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV99794','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'Unavailable','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => '-','affiliated_entries' => '-','phone_number' => 'Main Line: (210) 395-7269','created_at' => '2023-12-04 10:10:06','updated_at' => '2023-12-04 10:10:06','deleted_at' => NULL),
            array('id' => '70','name' => 'Alaska National Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV15905','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.alaskanational.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'Inland Valley Partners, LLC','phone_number' => 'Main: (415) 248-5030','created_at' => '2023-12-04 10:13:18','updated_at' => '2023-12-04 10:13:18','deleted_at' => NULL),
            array('id' => '71','name' => 'Alaska Timber Insurance Exchange','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV60728','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => '-','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (907) 225-9451','created_at' => '2023-12-04 10:15:53','updated_at' => '2023-12-04 10:15:53','deleted_at' => NULL),
            array('id' => '72','name' => 'Allianz','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV90043','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.agcs.allianz.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Coventry Provider Portal: https://www.coventryprovider.com','affiliated_entries' => '-','phone_number' => 'Main: (800) 870-8857','created_at' => '2023-12-04 10:18:18','updated_at' => '2023-12-04 10:18:18','deleted_at' => NULL),
            array('id' => '73','name' => 'Allied Claims Administration','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV01604','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'Unavailable','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (704) 365-7115 Bill Status: (704) 367-4855','created_at' => '2023-12-04 10:24:27','updated_at' => '2023-12-04 10:24:27','deleted_at' => NULL),
            array('id' => '74','name' => 'Alternative Service Concepts','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV60891','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://davies-group.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (615) 360-2800','created_at' => '2023-12-04 10:30:36','updated_at' => '2023-12-04 10:30:36','deleted_at' => NULL),
            array('id' => '75','name' => 'American Claims Management, Inc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV09319','start_time' => NULL,'end_time' => NULL,'email' => 'Bill Status: BillReview@ACMClaims.com','website' => 'https://www.acmclaims.com','bill_process_flow' => NULL,'bill_process_flow_note' => NULL,'is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Portal: https://portal.acmclaims.com/acmportal/login','affiliated_entries' => '-','phone_number' => 'Main: (866) 671-5042 Claim Inquiries: (866) 671-5042x2','created_at' => '2023-12-04 10:34:11','updated_at' => '2023-12-04 10:36:19','deleted_at' => NULL),
            array('id' => '76','name' => 'American Equity Underwriters','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV31799','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://www.amequity.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'American Equity Risk Services, AERS','phone_number' => 'Main: (504) 840-6500','created_at' => '2023-12-04 10:50:46','updated_at' => '2023-12-04 10:50:46','deleted_at' => NULL),
            array('id' => '77','name' => 'Amerisure','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV14599','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.amerisure.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (800) 257-1900 Claim Inquiries: (800) 257-1900','created_at' => '2023-12-04 10:56:43','updated_at' => '2023-12-04 10:56:43','deleted_at' => NULL),
            array('id' => '78','name' => 'Anchor Risk Management','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV25303','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'http://www.anchor-risk.com','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (214) 295-1600','created_at' => '2023-12-04 11:21:08','updated_at' => '2023-12-04 11:21:08','deleted_at' => NULL),
            array('id' => '79','name' => 'Applied Underwriters','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV47946','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.auw.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'North American Casualty, California Insurance Company, Continental Indemnity Company','phone_number' => 'Main: (877) 234-4420  Claim Inquiries: (877) 234-4420','created_at' => '2023-12-04 11:23:20','updated_at' => '2023-12-04 11:23:20','deleted_at' => NULL),
            array('id' => '80','name' => 'Argo - Argonaut Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV27096','start_time' => NULL,'end_time' => NULL,'email' => 'Bill Status: provider.relations@genexservices.com','website' => 'https://www.argolimited.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (800) 777-3602  Claim Inquiries: (800) 777-3602','created_at' => '2023-12-04 11:32:03','updated_at' => '2023-12-04 11:32:03','deleted_at' => NULL),
            array('id' => '81','name' => 'Armed Forces Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV21204','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: claims@afi.org','website' => 'https://www.afi.org/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'Armed Forces Insurance Exchange, AFIE, Armed Forces Insurance Agency, AFIA','phone_number' => '"Main Line: (800) 255-0187  Claim Inquiries: (800) 255-','created_at' => '2023-12-04 11:34:47','updated_at' => '2023-12-04 11:34:47','deleted_at' => NULL),
            array('id' => '82','name' => 'Arnold And Arnold, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV72528','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'http://www.arnoldoffice.com/index.html','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (800) 207-9301','created_at' => '2023-12-04 11:37:53','updated_at' => '2023-12-04 11:37:53','deleted_at' => NULL),
            array('id' => '83','name' => 'Arrowpoint Capital','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV89681','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.arrowpointcap.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (704) 522-2000  Claim Inquiries: (704) 522-2000','created_at' => '2023-12-04 11:44:10','updated_at' => '2023-12-04 11:44:10','deleted_at' => NULL),
            array('id' => '84','name' => 'Aspen Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV09404','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'Unavailable','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (972) 404-1615','created_at' => '2023-12-04 11:48:04','updated_at' => '2023-12-04 11:48:04','deleted_at' => NULL),
            array('id' => '85','name' => 'Associated Claims Administrators, Inc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV40730','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.aiamga.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 388-6268','created_at' => '2023-12-04 11:52:11','updated_at' => '2023-12-04 11:52:11','deleted_at' => NULL),
            array('id' => '86','name' => 'Assurance Resources, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV68440','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.ari-usa.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (713) 986-9377','created_at' => '2023-12-04 11:55:55','updated_at' => '2023-12-04 11:55:55','deleted_at' => NULL),
            array('id' => '87','name' => 'Athens Administrators','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV95392','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: reception@athensadmin.com','website' => 'https://www.athensadmin.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (866) 482-3535','created_at' => '2023-12-04 12:03:00','updated_at' => '2023-12-04 12:03:00','deleted_at' => NULL),
            array('id' => '88','name' => 'Atlantic Charter Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV01640','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.atlanticcharter.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (617) 488-6500','created_at' => '2023-12-04 12:11:05','updated_at' => '2023-12-04 12:11:05','deleted_at' => NULL),
            array('id' => '89','name' => 'Atlantic Pacific Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV09827','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.apins.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'CompAdvantage','phone_number' => 'Main Line: (800) 538-0487','created_at' => '2023-12-04 12:13:16','updated_at' => '2023-12-04 12:13:16','deleted_at' => NULL),
            array('id' => '90','name' => 'Atlas Financial Holdings','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV35002','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.atlas-fin.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 897-2551','created_at' => '2023-12-04 12:14:59','updated_at' => '2023-12-04 12:14:59','deleted_at' => NULL),
            array('id' => '91','name' => 'Avi Risk Services','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV88240','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://aviriskservices.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: ((61) 0) -687- x3869','created_at' => '2023-12-07 06:22:18','updated_at' => '2023-12-07 06:22:18','deleted_at' => NULL),
            array('id' => '92','name' => 'Babb, Inc.','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV40152','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.babbins.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 892-1015','created_at' => '2023-12-07 06:24:44','updated_at' => '2023-12-07 06:24:44','deleted_at' => NULL),
            array('id' => '93','name' => 'Benchmark Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV95944','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.benchmarkadministrators.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'S & C Claims Administrators','phone_number' => 'Main: (909) 843-9155','created_at' => '2023-12-07 06:27:48','updated_at' => '2023-12-07 06:27:48','deleted_at' => NULL),
            array('id' => '94','name' => 'Benetech, Inc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV89000','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://benetechadvantage.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (518) 283-8500','created_at' => '2023-12-07 06:29:21','updated_at' => '2023-12-07 06:29:21','deleted_at' => NULL),
            array('id' => '95','name' => 'Berkley Industrial Comp','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV03472','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.berkindcomp.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Main Line: (800) 448-5621 
          Claim Inquiries: (800) 448-5621 x3,1"','created_at' => '2023-12-07 06:32:08','updated_at' => '2023-12-07 06:32:08','deleted_at' => NULL),
            array('id' => '96','name' => 'Berkley Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV79610','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => '-','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => '-','affiliated_entries' => 'Great Divide Insurance Company','phone_number' => '-','created_at' => '2023-12-07 06:33:17','updated_at' => '2023-12-07 06:33:17','deleted_at' => NULL),
            array('id' => '97','name' => 'Berkley Mid-Atlantic Group','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV52809','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.wrbmag.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity does not receive bills, Third Party Bill Review receives bills directly','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Main Line: (800) 283-1153 
          Claim Inquiries: (800) 283-1153 x2,4 
          Bill Inquiries: (800) 283-1153 x2,3"','created_at' => '2023-12-07 06:35:01','updated_at' => '2023-12-07 06:35:01','deleted_at' => NULL),
            array('id' => '98','name' => 'Berkley Net Underwriters, LLC','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV28779','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: claimops@berkleynet.com','website' => 'https://www.berkleynet.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Main: (703) 586-6300 
          Claim Inquiries: (703) 586-6300 x1,2 
          Main - Alternate: (866) 915-4458"','created_at' => '2023-12-07 06:36:41','updated_at' => '2023-12-07 06:36:41','deleted_at' => NULL),
            array('id' => '99','name' => 'Berkley Risk Administrators Company, LLC','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV99472','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://www.berkleyrisk.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => '-','affiliated_entries' => '-','phone_number' => 'Main Line: (612) 766-3000','created_at' => '2023-12-07 06:38:34','updated_at' => '2023-12-07 06:38:34','deleted_at' => NULL),
            array('id' => '100','name' => 'Berkley Southeast Insurance Group','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV16960','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.berkleysig.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity does not receive bills, Third Party Bill Review receives bills directly','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Main Line: (855) 802-5273 
          Claim Inquiries: (855) 802-5273 x4 
          Bill Inquiries: (855) 802-5273 x3"','created_at' => '2023-12-07 06:40:34','updated_at' => '2023-12-07 06:40:34','deleted_at' => NULL),
            array('id' => '101','name' => 'Berkley Specialty Underwriting Managers','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV02261','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://www.berkleyentertainment.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'Berkley Environmental, Berkley Entertainment','phone_number' => 'Main: (800) 449-2024','created_at' => '2023-12-07 06:43:46','updated_at' => '2023-12-07 06:43:46','deleted_at' => NULL),
            array('id' => '102','name' => 'Biberk','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV03463','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: Claims@biBERK.com','website' => 'https://www.biberk.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (844) 472-0966 
          Claim Inquiries: (844) 472-0966 x2','created_at' => '2023-12-07 06:49:20','updated_at' => '2023-12-07 06:49:20','deleted_at' => NULL),
            array('id' => '103','name' => 'Bitco Insurance Companies','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV10236','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.bitco.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 475-4477','created_at' => '2023-12-07 06:50:47','updated_at' => '2023-12-07 06:50:47','deleted_at' => NULL),
            array('id' => '104','name' => 'Blair & Company','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV50189','start_time' => NULL,'end_time' => NULL,'email' => '-','website' => 'https://www.blairandco.net/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Claim Inquiries: claims@blairandco.net','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Not Provided','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 487-1263','created_at' => '2023-12-07 07:00:03','updated_at' => '2023-12-07 07:00:03','deleted_at' => NULL),
            array('id' => '105','name' => 'Bmi Benefits, Llc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV50488','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://bobmccloskey.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'Bob McCloskey Insurance','phone_number' => 'Main Line: ((80) 0) -445- x3126','created_at' => '2023-12-07 12:16:24','updated_at' => '2023-12-07 12:16:24','deleted_at' => NULL),
            array('id' => '106','name' => 'Brentwood Services Administrators, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV60908','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: claims.claims@bwood.com','website' => 'https://www.bwood.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity does not receive bills, Third Party Bill Review receives bills directly','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (800) 524-0604','created_at' => '2023-12-07 12:18:08','updated_at' => '2023-12-07 12:18:08','deleted_at' => NULL),
            array('id' => '107','name' => 'Brickstreet Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV08940','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.brickstreet.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => 'Encova Insurance, Motorists Insurance Group','phone_number' => 'Main: (866) 452-7425','created_at' => '2023-12-07 12:19:57','updated_at' => '2023-12-07 12:19:57','deleted_at' => NULL),
            array('id' => '108','name' => 'Broadspire Services, Inc.','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV73091','start_time' => NULL,'end_time' => NULL,'email' => 'customer_relations@choosebroadspire.com','website' => 'https://www.choosebroadspire.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Provider Portal: https://mymbrstatus.choosebroadspire.com','affiliated_entries' => 'Kemper Insurance Companies, Kemper Employer\'s Claims Services','phone_number' => 'Main: (800) 800-7885','created_at' => '2023-12-07 12:43:00','updated_at' => '2023-12-07 12:43:00','deleted_at' => NULL),
            array('id' => '109','name' => 'Brotherhood Mutual Insurance','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV07091','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: claims@brotherhoodmutual.com','website' => 'https://www.brotherhoodmutual.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => '"Main: (800) 333-3735 
          Claim Inquiries: (800) 333-3371"','created_at' => '2023-12-07 12:44:36','updated_at' => '2023-12-07 12:44:36','deleted_at' => NULL),
            array('id' => '110','name' => 'BSI Companies','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV60060','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://bsicompanies.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (864) 370-0711','created_at' => '2023-12-07 12:46:04','updated_at' => '2023-12-07 12:46:04','deleted_at' => NULL),
            array('id' => '111','name' => 'Builders Insurance Group','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV13904','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.bldrs.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (678) 309-4000','created_at' => '2023-12-07 12:51:10','updated_at' => '2023-12-07 12:51:10','deleted_at' => NULL),
            array('id' => '112','name' => 'Builders Mutual Insurance Company','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV00508','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.buildersmutual.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives bills and forwards to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 809-4861','created_at' => '2023-12-07 12:54:09','updated_at' => '2023-12-07 12:54:09','deleted_at' => NULL),
            array('id' => '113','name' => 'Cabot Risk Strategies, LLC','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV94605','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.cabotrisk.com/','bill_process_flow' => NULL,'bill_process_flow_note' => '-','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main Line: (800) 222-5963','created_at' => '2023-12-07 12:55:55','updated_at' => '2023-12-07 12:55:55','deleted_at' => NULL),
            array('id' => '114','name' => 'California Claims Management Services, Inc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV39977','start_time' => NULL,'end_time' => NULL,'email' => 'Claim Inquiries: shirotsu@ccms-tpa.com','website' => 'https://ccms-tpa.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Entity receives, reviews and processes bills','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (310) 542-5130 
          Claim Inquiries: (310) 542-5130 x2','created_at' => '2023-12-07 12:57:21','updated_at' => '2023-12-07 12:57:21','deleted_at' => NULL),
            array('id' => '115','name' => 'California Insurance Guarantee Association','alias' => NULL,'company_type_id' => '3','description' => '-','payer_id' => 'MV69924','start_time' => NULL,'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.ciga.org/','bill_process_flow' => NULL,'bill_process_flow_note' => 'Claims Administrator forwards bills to Third Party Bill Review','is_active' => '1','admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL,'bill_portal' => 'Unavailable','affiliated_entries' => '-','phone_number' => 'Main: (818) 844-4300','created_at' => '2023-12-07 13:02:15','updated_at' => '2023-12-07 13:02:15','deleted_at' => NULL),
            array('id' => '116','name' => 'Cannon Cochran Management Services Inc','alias' => NULL,'company_type_id' => '1','description' => '-','payer_id' => 'MV04029','start_time' => NULL,
            'end_time' => NULL,'email' => 'Unavailable','website' => 'https://www.ccmsi.com/','bill_process_flow' => NULL,'bill_process_flow_note' => 'kjnkjn','is_active' => '1', 'admin_fax_no' => 'Not Provided','admin_address' => '-','clearing_house' => '-','time_zone_type' => NULL, 'bill_portal' => 'Unavailable','affiliated_entries' => 'State of North Carolina, Illinois Public Risk Fund',
            'phone_number' => 'Main: (800) 252-5059','created_at' => '2023-12-07 13:05:57','updated_at' => '2023-12-07 13:16:06','deleted_at' => NULL)
          );
           foreach ($claimAdministrators as $claimAdmin) {
            ClaimAdministrator::create(['name'=>$claimAdmin['name'], 'alias'=>$claimAdmin['alias'],'company_type_id'=>$claimAdmin['company_type_id'],'description'=>$claimAdmin['description'], 'payer_id'=>$claimAdmin['payer_id'],'start_time'=>$claimAdmin['start_time'],'end_time'=>$claimAdmin['end_time'],'email'=>$claimAdmin['email'],'website'=>$claimAdmin['website'],'bill_process_flow'=>$claimAdmin['bill_process_flow'],'bill_process_flow_note'=>$claimAdmin['bill_process_flow_note'],'is_active'=>$claimAdmin['is_active'],
            'bill_portal'=>$claimAdmin['bill_portal'],'affiliated_entries'=>$claimAdmin['affiliated_entries'],'phone_number'=>$claimAdmin['phone_number'],'created_at'=>$claimAdmin['created_at'],'updated_at'=>$claimAdmin['updated_at']]);
          }
    }
}
